[github_app]
pr_commands = [
    "/describe --pr_description.final_update_message=false",
    "/review --pr_reviewer.num_code_suggestions=0",
    "/improve",
]
handle_push_trigger = true
push_commands = [
    "/describe",
    "/review --pr_reviewer.num_code_suggestions=0 --pr_reviewer.final_update_message=false",
]

[config]
model = "huggingface/meta-llama/Llama-2-7b-chat-hf"
model_turbo = "huggingface/meta-llama/Llama-2-7b-chat-hf"
HUGGINGFACE = { key = "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", api_base = "https://api-inference.huggingface.co/models/" }
