name: Codium PR Agent

on: [pull_request]

jobs:
  codium-pr-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pr-agent
        run: |
          python -m pip install --upgrade pip
          pip install pr-agent

      - name: Run Codium PR Agent
        run: |
          python run_pr_agent.py
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_USER_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          COMMAND: "/review"